import type { Artifact, Thread } from '../types';
import type { UploadResult } from './integration/integrations';

const NOTEBOOKLM_URL = 'https://notebooklm.google.com/';
const NOTEBOOKLM_ROOT_FOLDER = 'GEMINI/NotebookLM';

export interface NotebookLmSourcePackInput {
  title: string;
  artifacts?: Artifact[];
  thread?: Thread | null;
  createdAt?: Date;
}

export interface NotebookLmSourcePack {
  title: string;
  fileName: string;
  folderPath: string;
  content: string;
}

export interface UploadNotebookLmSourcePackOptions {
  accessToken: string;
  pack: NotebookLmSourcePack;
  uploadFile: (
    accessToken: string,
    name: string,
    mimeType: string,
    blob: Blob,
    folderPath?: string
  ) => Promise<UploadResult>;
}

export interface NotebookLmHandoffResult extends UploadResult {
  notebookLmUrl: string;
}

function pad2(value: number): string {
  return value < 10 ? `0${value}` : String(value);
}

function formatDate(date: Date): string {
  return `${date.getUTCFullYear()}-${pad2(date.getUTCMonth() + 1)}-${pad2(date.getUTCDate())}`;
}

function slugify(value: string): string {
  const slug = value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return slug || 'notebooklm-source-pack';
}

function appendSection(lines: string[], heading: string, body: string): void {
  const trimmed = body.trim();
  if (!trimmed) return;
  lines.push('', heading, '', trimmed);
}

function artifactMetadataLines(artifact: Artifact): string[] {
  const lines = [
    `- Type: ${artifact.type}`,
    `- Created: ${new Date(artifact.createdAt).toISOString()}`,
  ];
  if (artifact.mimeType) lines.push(`- MIME type: ${artifact.mimeType}`);
  if (artifact.driveFileId) lines.push(`- Drive file ID: \`${artifact.driveFileId}\``);
  return lines;
}

export function buildNotebookLmSourcePack(input: NotebookLmSourcePackInput): NotebookLmSourcePack {
  const createdAt = input.createdAt ?? new Date();
  const date = formatDate(createdAt);
  const title = input.title.trim() || 'NotebookLM Source Pack';
  const lines: string[] = [
    `# ${title}`,
    '',
    `Created: ${createdAt.toISOString()}`,
    '',
    '> Source pack generated by GEMINI for macOS. NotebookLM has no stable public REST API; add this Drive file manually as a NotebookLM source.',
  ];

  for (const artifact of input.artifacts ?? []) {
    lines.push('', `## Artifact: ${artifact.title}`, '', ...artifactMetadataLines(artifact), '');
    appendSection(lines, '### Content', artifact.content);
  }

  if (input.thread) {
    lines.push('', `## Thread: ${input.thread.title}`, '');
    for (const message of input.thread.messages) {
      const role = message.role === 'model' ? 'Gemini' : 'User';
      appendSection(lines, `### ${role}`, message.content);
    }
  }

  return {
    title,
    fileName: `${slugify(title)}.md`,
    folderPath: `${NOTEBOOKLM_ROOT_FOLDER}/${date}`,
    content: `${lines.join('\n').replace(/\n{4,}/g, '\n\n\n')}\n`,
  };
}

export async function uploadNotebookLmSourcePack(
  options: UploadNotebookLmSourcePackOptions
): Promise<NotebookLmHandoffResult> {
  const blob = new Blob([options.pack.content], { type: 'text/markdown' });
  const upload = await options.uploadFile(
    options.accessToken,
    options.pack.fileName,
    'text/markdown',
    blob,
    options.pack.folderPath
  );

  return {
    ...upload,
    notebookLmUrl: NOTEBOOKLM_URL,
  };
}

export const NOTEBOOKLM_HANDOFF_URL = NOTEBOOKLM_URL;
